### ISSUE TITLE
ImportError: cannot import name 'get_aqm_pulses'

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/hax#56]
Seeing this error running within ```cax``` in ```pax_v6.2.0``` environment (hax v1.2.0):
```
Traceback (most recent call last):
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/cax-4.10.5-py3.4.egg/cax/main.py", line 131, in main
    task.go(args.run)
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/cax-4.10.5-py3.4.egg/cax/task.py", line 65, in go
    self.each_run()
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/cax-4.10.5-py3.4.egg/cax/tasks/process_hax.py", line 101, in each_run
    self.run_doc['detector'])
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/cax-4.10.5-py3.4.egg/cax/tasks/process_hax.py", line 53, in _process_hax
    init_hax(in_location, pax_version, out_location)   # may initialize once only
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/cax-4.10.5-py3.4.egg/cax/tasks/process_hax.py", line 25, in init_hax
    minitree_paths = [out_location])
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/hax-1.2.0-py3.4.egg/hax/__init__.py", line 66, in init
    update_treemakers()
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/hax-1.2.0-py3.4.egg/hax/minitrees.py", line 123, in update_treemakers
    __import__('hax.treemakers.%s' % module_name, globals=globals())
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/ROOT.py", line 301, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/project/lgrandi/anaconda3/envs/pax_v6.2.0/lib/python3.4/site-packages/hax-1.2.0-py3.4.egg/hax/treemakers/trigger.py", line 6, in <module>
    from hax.trigger_data import get_aqm_pulses
ImportError: cannot import name 'get_aqm_pulses'
```

**Comment by JelleAalbers** [comment]
I just tried `import hax` and `hax.__version__` in `pax_v6.2.0` on midway, it gives me `1.1.1`. Perhaps the deployment of hax did not fully succeed?

**Comment by pdeperio** [comment]
I don't see ```1.1.1``` when I do:
```
export PATH="/project/lgrandi/anaconda3/bin:$PATH"
source activate pax_v6.2.0
python -c "import hax;print(hax.__version__)"
1.2.0
```
and ```conda list``` shows only ```1.2.0```. The backtrace above also shows it's using the ```1.2.0``` package. 

It's not a constant problem, but happens sporadically, for example here:
```
/project/lgrandi/xenon1t/cax/5461_v6.2.0/cax.log
```
